name: Docker Image Nightly Build CI

on:
  push:
    branches:
      - cron_build
  pull_request:
    paths: .github/workflows/docker-nightly-build.yml

  workflow_dispatch:

  schedule:
    # run daily 0:00
    - cron: '0 0 * * *'

env:
  ORG: timescaledev
  TS_VERSION: main

jobs:

  build:
    name: PG${{ matrix.pg }} ${{ matrix.platform }}
    runs-on: ${{ matrix.runs_on }}
    strategy:
      fail-fast: false
      matrix:
        pg: [16, 17, 18]
        platform: [ linux/amd64, linux/arm64 ]
        include:
          - platform: linux/amd64
            runs_on: runs-on/fleet=linux-8cpu-x64/env=ue1
          - platform: linux/arm64
            runs_on: runs-on/fleet=linux-8cpu/env=ue1
    steps:
      - uses: runs-on/action@46910bf61b41721b0579f237e186afb35477007a # v2.3.0

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: ./.github/actions/build-platform
        with:
          pg: ${{ matrix.pg }}
          platform: ${{ matrix.platform }}
          ts_version: ${{ env.TS_VERSION }}
          org: ${{ env.ORG }}
          dockerhub_username: ${{ secrets.ORG_DOCKER_HUB_USERNAME }}
          dockerhub_token: ${{ secrets.ORG_DOCKER_HUB_ACCESS_TOKEN }}

  manifest:
    name: Manifest PG${{ matrix.pg }}
    needs: [ build ]
    runs-on: runs-on/fleet=linux-2cpu/env=ue1
    strategy:
      fail-fast: false
      matrix:
        pg: [16, 17, 18]
    steps:
      - uses: runs-on/action@46910bf61b41721b0579f237e186afb35477007a # v2.3.0

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: ./.github/actions/publish-manifest
        with:
          pg: ${{ matrix.pg }}
          ts_version: ${{ env.TS_VERSION }}
          org: ${{ env.ORG }}
          tag: -t ${{ env.ORG }}/timescaledb:nightly-pg${{ matrix.pg }}
          dockerhub_username: ${{ secrets.ORG_DOCKER_HUB_USERNAME }}
          dockerhub_token: ${{ secrets.ORG_DOCKER_HUB_ACCESS_TOKEN }}
